### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by marvin2k** [rock-drivers/drivers-canbus#1]
Hi,

while playing around with clang, the tool found [this](https://github.com/rock-drivers/drivers-canbus/blob/master/canbus-2web.cc#L178) to be an invitation to hidden magic:

```bash
.../drivers/canbus/canbus-2web.cc:178:39: warning: use of logical '&&' with constant
      operand [-Wconstant-logical-operand]
    result.size = canMsg.rtr_mode_len && 0x0F;
                                      ^  ~~~~
```

Meanwhile, [this](https://github.com/rock-drivers/drivers-canbus/blob/master/canbus-2web.cc#L151) is a plain memory leak.

Later, scan-build reports these [two](https://github.com/rock-drivers/drivers-canbus/blob/master/canbus-2web.cc#L221) [-Wsign-compare](https://github.com/rock-drivers/drivers-canbus/blob/master/canbus-2web.cc#L206)s and a value never [read](https://github.com/rock-drivers/drivers-canbus/blob/master/tools/hcantool.c#L334).

Just reporting, for educational purpose ;-)

**Comment by jrenken** [comment]
Fixed
